export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const ADD_TO_CART_RESET = "ADD_TO_CART_RESET";

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAIL = "UPDATE_CART_FAIL";
export const UPDATE_CART_RESET = "UPDATE_CART_RESET";

export const GET_CART_ITEMS_REQUEST = "GET_CART_ITEMS_REQUEST";
export const GET_CART_ITEMS_SUCCESS = "GET_CART_ITEMS_SUCCESS";
export const GET_CART_ITEMS_FAIL = "GET_CART_ITEMS_FAIL";

export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";
export const REMOVE_CART_ITEM_FAIL = "REMOVE_CART_ITEM_FAIL";
export const REMOVE_CART_ITEM_RESET = "REMOVE_CART_ITEM_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
