export const ADD_NEW_COUPON_REQUEST = "ADD_NEW_COUPON_REQUEST";
export const ADD_NEW_COUPON_SUCCESS = "ADD_NEW_COUPON_SUCCESS";
export const ADD_NEW_COUPON_FAIL = "ADD_NEW_COUPON_FAIL";

export const UPDATE_COUPON_REQUEST = "UPDATE_COUPON_REQUEST";
export const UPDATE_COUPON_SUCCESS = "UPDATE_COUPON_SUCCESS";
export const UPDATE_COUPON_FAIL = "UPDATE_COUPON_FAIL";

export const DELETE_COUPON_REQUEST = "DELETE_COUPON_REQUEST";
export const DELETE_COUPON_SUCCESS = "DELETE_COUPON_SUCCESS";
export const DELETE_COUPON_FAIL = "DELETE_COUPON_FAIL";

export const DEACTIVE_COUPON_REQUEST = "DEACTIVE_COUPON_REQUEST";
export const DEACTIVE_COUPON_SUCCESS = "DEACTIVE_COUPON_SUCCESS";
export const DEACTIVE_COUPON_FAIL = "DEACTIVE_COUPON_FAIL";

export const GET_ALL_COUPONS_REQUEST = "GET_ALL_COUPONS_REQUEST";
export const GET_ALL_COUPONS_SUCCESS = "GET_ALL_COUPONS_SUCCESS";
export const GET_ALL_COUPONS_FAIL = "GET_ALL_COUPONS_FAIL";

export const VALIDATE_COUPON_REQUEST = "VALIDATE_COUPON_REQUEST";
export const VALIDATE_COUPON_SUCCESS = "VALIDATE_COUPON_SUCCESS";
export const VALIDATE_COUPON_FAIL = "VALIDATE_COUPON_FAIL";

export const REMOVE_COUPON_REQUEST = "REMOVE_COUPON_REQUEST";
export const REMOVE_COUPON_SUCCESS = "REMOVE_COUPON_SUCCESS";
export const REMOVE_COUPON_FAIL = "REMOVE_COUPON_FAIL";

export const RESET_COUPON = "RESET_COUPON";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
