export const ADD_TO_FAVORUITE_REQUEST = "ADD_TO_FAVORUITE_REQUEST";
export const ADD_TO_FAVORUITE_SUCCESS = "ADD_TO_FAVORUITE_SUCCESS";
export const ADD_TO_FAVORUITE_FAIL = "ADD_TO_FAVORUITE_FAIL";
export const RESET_ADD_TO_FAVOURITE = "RESET_ADD_TO_FAVOURITE";

export const GET_FAVORUITE_REQUEST = "GET_FAVORUITE_REQUEST";
export const GET_FAVORUITE_SUCCESS = "GET_FAVORUITE_SUCCESS";
export const GET_FAVORUITE_FAIL = "GET_FAVORUITE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
